### ISSUE TITLE
Improve srcset documentation

### ISSUE THREAD

**Issue by darren131** [sjelfull/imgix#1]
Hi,

Can you please expand a bit on the srcset documentation?

Thanks!
Darren

**Comment by sjelfull** [comment]
Hi @darren131,

Currently don't have much time, so it will probably be some time before I get to it.

Feel free to send a pull request.

**Comment by skramstad** [comment]
Hi @darren131 

Hope this code helps you!

First set som transforms, this example is only scaling the width of the image. You can read more about the API [here](https://docs.imgix.com/apis/url). We also format, compress [(auto)](https://docs.imgix.com/apis/url/auto), convert the Color Space [(cs)](https://docs.imgix.com/apis/url/format/cs) to srgb and then sharpen the image [(sharp)](https://docs.imgix.com/apis/url/adjustment/sharp).

```
{% set transforms = [
    {
        w: 800,
        auto: 'format,compress',
        cs: 'srgb',
        sharp: 10
    },
    {
        w: 600,
        auto: 'format,compress',
        cs: 'srgb',
        sharp: 10
    },
    {
        w: 400,
        auto: 'format,compress',
        cs: 'srgb',
        sharp: 10
    },
    {
        w: 291,
        auto: 'format,compress',
        cs: 'srgb',
        sharp: 10
    }
] %}

{% set transformedImage = craft.imgix.transformImage( image, transforms) %}
{{ transformedImage.srcset({ 'class': 'any-CSS-class', 'alt': image.title, 'itemprop': 'image' }) }}
```

If you want to crop the image
```
    { 
        w: 800,
        h: 600,
        auto: 'format,compress',
        crop: 'center,center',
        fit: 'crop',
        cs: 'srgb',
        sharp: 10
    }
```

**Comment by skramstad** [comment]
How do I use defaultSettings? Lets say I use the example above but instead I want to use _(instead of repeating myself)_:
```
{% set imageOptions = 
    {
        cs: 'srgb',
        auto: 'format,compress',
        crop: 'top,right',
        fit: 'crop',
        cs: 'srgb',
        sharp: 80
    }
%}
```

I thought this would work... but no luck
```
{% set transformedImage = craft.imgix.transformImage( image, imageSizes, imageOptions ) %}
```

**Comment by sjelfull** [comment]
@skramstad I think that was a bug. Could you try again?

**Comment by skramstad** [comment]
@sjelfull I believe this issue was because it was not implemented yet. But it's working now!

**Comment by sjelfull** [comment]
@skramstad Kool. Yeah, that is the "bug" I had in mind 😁
