### ISSUE TITLE
Use composer

### ISSUE THREAD

**Issue by skramstad** [sjelfull/imgix#12]
Hi.

Could you please make this available with composer? Just like imgix craft 3 version 🥇 

Thanks!

**Comment by sjelfull** [comment]
I've published it on Packagist now. Could you test it?

**Comment by skramstad** [comment]
I did, but the imgix plugin is in folder /vendor/sjelfull/imgix and not craft/plugins
So when that is fixed, we're good to go I recon 👍

**Comment by sjelfull** [comment]
I think it was missing a dependency. Added `"composer/installers": "~1.0"` now.

Could you try again by removing and adding it?

**Comment by skramstad** [comment]
Awesome! Works if you tag it with a new release. I had to set "sjelfull/imgix": "dev-master" to make it work.

**Comment by sjelfull** [comment]
Great, new tag added.
