### ISSUE TITLE
imgix breaks on live server

### ISSUE THREAD

**Issue by AbbeyDesign** [sjelfull/imgix#14]
I get this error on a live site and the template stops rendering as soon as it calls imgix plugin. Local site does not see an issue

`Parse error: syntax error, unexpected '?' in /xxxxxx/xxxxxx/xxxxxx/public_html/xxxxxx/plugins/imgix/models/ImgixModel.php on line 222`

**Comment by sjelfull** [comment]
I assume you are running a lower version than PHP 7. The plugin uses some PHP 7 features, but I could probably replace them to make it compatible with PHP 5.4 >, even though end-of-life for PHP 5.6 is Jan 1st 2018.

**Comment by AbbeyDesign** [comment]
oops... that was it, old server that I never updated the php on. Thanks.
