### ISSUE TITLE
width + ratio transform settings produce improperly sized images

### ISSUE THREAD

**Issue by jeremyfrank** [sjelfull/imgix#16]
In the third image example below from the readme, where only the width and ratio parameters are present, the resulting image from imgix doesn't conform to the supplied aspect ratio. Also, the ratio parameter is sent in the request but it a parameter that imgix understands.

These transform options:
```
{% set thirdImage = craft.imgix.transformImage( asset, { width: 1920, ratio: 16/9}) %}
```

Produce this imgix querystring:
```
?fp-x=0.5&fp-y=0.5&ixlib=php-1.1.0&ratio=1.77777777778&w=1920
```

Both w (width) and h (height) parameters should be present along with a fit parameter set to crop to ensure a proper output (when only width and ratio are supplied):
```
?fp-x=0.5&fp-y=0.5&ixlib=php-1.1.0&ratio=1.77777777778&w=1920&h=1080&fit=crop
```

**Comment by skramstad** [comment]
Hi.

Do you include fit and crop in your config?

i.e:
`fit: 'crop',
crop: 'center,center',`

If not set the ratio will not work.
You can read more about crop settings here: https://docs.imgix.com/apis/url/size/crop

**Comment by terbolous** [comment]
@jeremyfrank I'm not able to reproduce, what's the plugin version and craft version?

Automatically appending `fit=crop` was dropped and left for the developer to add, basically I didn't want to make assumptions that `fit=crop` was what everyone wanted.
