### ISSUE TITLE
Craft v4 support

### ISSUE THREAD

**Issue by anchovy** [sjelfull/imgix#25]
Hi, Is this plugin going to be upgraded to support Craft V4? Any timeline for this?
Thanks in advance.

**Comment by karensg** [comment]
That would be great indeed!

**Comment by engram-design** [comment]
@sjelfull Just let me know if you'd like a hand maintaining this plugin for Craft 4 with [Verbb](https://verbb.io/craft-3)

**Comment by sjelfull** [comment]
This is the Craft 2 version - The Craft 3+ version has been updated for Craft 4: https://github.com/sjelfull/craft3-imgix
