### ISSUE TITLE
Animated GIF support?

### ISSUE THREAD

**Issue by stursby** [sjelfull/Imgix#4]
I see on Imgix's website that "Animated GIF functionality is currently in Beta." [[docs](https://docs.imgix.com/apis/url/format/fm)] but I was wondering if this library support animated GIFs out of the box? Thanks!

**Comment by sjelfull** [comment]
I haven't tested. Test it and report back?

**Comment by stursby** [comment]
@sjelfull So I've got ImageMagick installed at GIF are correctly uploading in Craft and off to S3, however they seem to be frozen on the first frame on Imgix.

ImageMagick installed
![image](https://user-images.githubusercontent.com/527849/30596877-0d840e00-9d1b-11e7-9ddd-34e74c12f734.png)

Uploaded correctly in Craft
![image](https://user-images.githubusercontent.com/527849/30597029-64259288-9d1b-11e7-8a8d-b7351df3c968.png)

...and still groovin' on S3
https://s3-us-west-2.amazonaws.com/collemcvoy-imgix/images/doing-big-things.gif?mtime=20170918211352

But no luck on Imgix 😢 
https://collemcvoy.imgix.net/doing-big-things.gif?auto=format&cs=strip&ixlib=php-1.1.0

**Comment by daletom** [comment]
Hey @stursby @sjelfull as you mentioned above, our animated GIFs are in beta so they are turned off on default for sources/accounts.  I have enabled animated gifs for the collemcvoy source.  I have also purged that GIF, but if it doesnt work try hard refreshing your browser.  If you need it on another source just ping me at tom_imgix on craft slack or tom@imgix.com.  Also, I would recommend using gifq, that is our parameter that modifies the quality of a gif.  It is different than our image quality parameter, the higher the number the MORE compression.  So, for example: https://collemcvoy.imgix.net/doing-big-things.gif?auto=format,compress&cs=strip&ixlib=php-1.1.0&gifq=55

If you want to think of different ways to lower the size of the gifs, you can skip every 3rd frame (skip=3) and that would help as well.  Or you can even get rid of the auto=format and do a fm=mp4, then just modify in the browser to auto:play auto:loop and remove the player controls.  No one will be able to tell its not a gif :)

**Comment by stursby** [comment]
@daletom Oh, awesome, thanks! I actaully just tried some new GIF and they work now! Ok, I will mess around with the skip and fm params. Awesome, you rock! 👍

**Comment by tedw** [comment]
@daletom The docs say “Animated GIF functionality is currently available to all Premium imgix customers” but the pricing page doesn’t mention “premium” anywhere. Would my client need to upgrade to the “Volume Pricing” plan starting at $500/mo to get this functionality or is it possible to just add animated GIF support to the “Pay As You Go” plan? Thanks!

**Comment by daletom** [comment]
@tedw I can just add it to your pay as you go plan.  Whats the name of your account? Is it for CompTIA?

**Comment by tedw** [comment]
@daletom Hey, sorry for the late reply! My wife had a baby the day after you sent that message so I’ve been out on paternity leave. Yes, it’s the CompTIA account, thanks! The site actually launches tomorrow.

**Comment by daletom** [comment]
Hey Ted, congrats! My wife is actually due in 2 days, so I'm in that mode as well.  I just turned on the GIFs, they should activate in about 5 minutes.  If they don't work, try using a different parameter (like a different size) to see if it works then. If it does, that means the the other version just needs to be purged.  Good luck with the launch of the site!

**Comment by tedw** [comment]
@daletom Oh wow, congrats to you too! Hope everything goes smoothly.

GIFs work great now, thanks again for the help!

**Comment by bimusiek** [comment]
Is it possible to enable it for Stamp Software LTD as well please? :) Or is it an option somewhere in settings to enable animated GIFs and I cannot find it?

**Comment by daletom** [comment]
sure thing @bimusiek , just activated. Should be working in 10 minutes. If it doesn't work after 10 minutes, it might be because you are trying the same url that did not work and it got cached. Try adjusting one of the APIs differently or just purge it.
