### ISSUE TITLE
Rename to imgix? Small letter 'i'

### ISSUE THREAD

**Issue by nilsnh** [sjelfull/imgix#7]
A minor nitpick but OS/X has a very relaxed attitude towards letter casing. It threw me off for a bit that I saw the plugin locally but not in the remote environment. Renaming the plugin solved it. It does ask to rename the folder in the readme but renaming the project to imgix could remove a lot of future head scratching for new users. :)

**Comment by sjelfull** [comment]
@nilsnh Hehe, thanks, it bothered me too :)

**Comment by AbbeyDesign** [comment]
Yeah, I ran into this issue today. Spent a couple of hours trying to figure out why my live site was not loading the plugin. Mac OS did not care about the "I", the live server did. Docs say to rename and I just removed the "-master" without even noticing the capitalization.

**Comment by sjelfull** [comment]
Yeah, its stupid. Have renamed it now.
